export const IPC_CHANNELS = {
  GET_SESSION: 'wallet:get-session',
  CREATE_WALLET: 'wallet:create',
  IMPORT_WALLET: 'wallet:import',
  UNLOCK: 'wallet:unlock',
  LOCK: 'wallet:lock',
  GET_MNEMONIC: 'wallet:get-mnemonic',
  GET_BALANCE: 'wallet:get-balance',
  SEND_PREVIEW: 'wallet:send-preview',
  SEND: 'wallet:send',
  GET_TRANSACTIONS: 'wallet:get-transactions',
  REFRESH_TRANSACTIONS: 'wallet:refresh-transactions',
  UPDATE_TX_NOTE: 'wallet:update-tx-note',
  GET_ADDRESS_BOOK: 'wallet:get-address-book',
  ADD_ADDRESS_BOOK: 'wallet:add-address-book',
  REMOVE_ADDRESS_BOOK: 'wallet:remove-address-book',
  GET_SETTINGS: 'wallet:get-settings',
  UPDATE_SETTINGS: 'wallet:update-settings',
  CHANGE_PASSWORD: 'wallet:change-password',
  ADD_ACCOUNT: 'wallet:add-account',
  RENAME_ACCOUNT: 'wallet:rename-account',
  REMOVE_ACCOUNT: 'wallet:remove-account',
  EXPORT_VAULT: 'wallet:export-vault',
  EXPORT_BACKUP: 'wallet:export-backup',
  DELETE_VAULT: 'wallet:delete-vault',
  GENERATE_QR: 'wallet:generate-qr',
  VALIDATE_ADDRESS: 'wallet:validate-address',
  TOUCH_ACTIVITY: 'wallet:touch-activity',
  GET_PRICES: 'wallet:get-prices',
  GET_TRON_RESOURCES: 'wallet:get-tron-resources',
  GET_FEE_ESTIMATE: 'wallet:get-fee-estimate',
  GET_MULTISIG: 'wallet:get-multisig',
  ADD_MULTISIG: 'wallet:add-multisig',
  REMOVE_MULTISIG: 'wallet:remove-multisig',
  CHECK_UPDATES: 'wallet:check-updates',
  DOWNLOAD_UPDATE: 'wallet:download-update',
  INSTALL_UPDATE: 'wallet:install-update',
  SCAN_HARDWARE: 'wallet:scan-hardware',
  GET_HARDWARE_ADDRESS: 'wallet:get-hardware-address',
  DEPLOY_MULTISIG: 'wallet:deploy-multisig',
  FINALIZE_WALLET_SETUP: 'wallet:finalize-setup',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
